#src/main/resources/application-prod.properties
#spring.profiles.active=prod
#server.port=8080

#Database (use PostgreSQL for production)
# application.properties
spring.datasource.url=jdbc:mysql://localhost:3306/dsa_scheduler_prod
spring.datasource.username=root
spring.datasource.password=Selim@123

# For production, you might want to add:
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# JPA
spring.jpa.show-sql=false


# Thymeleaf
spring.thymeleaf.cache=true
spring.thymeleaf.mode=HTML

# Logging
logging.level.com.yourpackage=INFO
logging.file.name=/var/log/dsa-scheduler/app.log